apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skusobny-projekt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vikirajnakova-code/my-infra-gitops.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
